"""H3 Reference Turbo clip lengths, reference limits, and aspect ratios."""

MAX_PROMPT_CHARACTERS = 8_000

MIN_CLIP_SECONDS = 5.0

MAX_CLIP_SECONDS = 15.084

DEFAULT_CLIP_SECONDS = 6.0

STEP_CLIP_SECONDS = 0.001

OPTIONS_ASPECT = ["16:9", "1:1", "9:16", "4:3"]

DEFAULT_ASPECT = "16:9"

REFERENCE_SOCKET_COUNT = 6

MAX_REFERENCE_MEBIBYTES = 25

MAX_REFERENCE_PIXELS = 25_000_000

MIN_REFERENCE_ASPECT_RATIO = 0.25

MAX_REFERENCE_ASPECT_RATIO = 4.0

__all__ = [
    "DEFAULT_ASPECT",
    "DEFAULT_CLIP_SECONDS",
    "MAX_CLIP_SECONDS",
    "MAX_PROMPT_CHARACTERS",
    "MAX_REFERENCE_ASPECT_RATIO",
    "MAX_REFERENCE_MEBIBYTES",
    "MAX_REFERENCE_PIXELS",
    "MIN_CLIP_SECONDS",
    "MIN_REFERENCE_ASPECT_RATIO",
    "OPTIONS_ASPECT",
    "REFERENCE_SOCKET_COUNT",
    "STEP_CLIP_SECONDS",
]
