"""Describe reviewed Reactor model identities and live capabilities."""

from .generation.session import MAX_PROMPT_CHARACTERS
from .generation.video import MAX_EDIT_PROMPT_CHARACTERS
from .generation.fast import MAX_PROMPT_CHARACTERS as MAX_FAST_PROMPT_CHARACTERS
from .generation.turbo import MAX_PROMPT_CHARACTERS as MAX_TURBO_PROMPT_CHARACTERS
from .generation.world import LINGBOT_CAMERA_AXES, LINGBOT_WORLD_CAMERA_AXES, MAX_WORLD_PROMPT_CHARACTERS

MODEL_IDENTITIES = {
    "fast-h3": {
        "guide_slug": "fast-h3",
        "connection_name": "reactor/fast-h3",
        "title": "Fast H3",
        "max_prompt_characters": MAX_FAST_PROMPT_CHARACTERS,
        "prompt_kind": "scene",
        "is_empty_prompt_allowed": False,
        "camera_axes": (),
        "prompt_command": "set_prompt",
        "has_audio_prompt": False,
        "has_pointer": False,
        "has_prompt_passthrough": False,
    },
    "h3-reference-to-video-turbo-realtime": {
        "guide_slug": "h3-reference-to-video-turbo-realtime",
        "connection_name": "reactor/h3-reference-to-video-turbo-realtime",
        "title": "H3 Reference Turbo Realtime",
        "max_prompt_characters": MAX_TURBO_PROMPT_CHARACTERS,
        "prompt_kind": "scene",
        "is_empty_prompt_allowed": False,
        "camera_axes": (),
        "prompt_command": "set_prompt",
        "has_audio_prompt": False,
        "has_pointer": False,
        "has_prompt_passthrough": False,
    },
    "visko-orbis-stable": {
        "guide_slug": "visko-orbis-stable",
        "connection_name": "reactor/visko-orbis-stable",
        "title": "Visko Stable",
        "max_prompt_characters": MAX_PROMPT_CHARACTERS,
        "prompt_kind": "scene",
        "is_empty_prompt_allowed": False,
        "camera_axes": (),
        "prompt_command": "set_prompt",
        "has_audio_prompt": True,
        "has_pointer": False,
        "has_prompt_passthrough": True,
    },
    "visko-orbis-dynamic": {
        "guide_slug": "visko-orbis-dynamic",
        "connection_name": "reactor/visko-orbis-dynamic",
        "title": "Visko Dynamic",
        "max_prompt_characters": MAX_PROMPT_CHARACTERS,
        "prompt_kind": "scene",
        "is_empty_prompt_allowed": False,
        "camera_axes": (),
        "prompt_command": "set_prompt",
        "has_audio_prompt": True,
        "has_pointer": False,
        "has_prompt_passthrough": True,
    },
    "helios": {
        "guide_slug": "helios",
        "connection_name": "reactor/helios",
        "title": "Helios",
        "max_prompt_characters": MAX_PROMPT_CHARACTERS,
        "prompt_kind": "scene",
        "is_empty_prompt_allowed": False,
        "camera_axes": (),
        "prompt_command": "set_prompt",
        "has_audio_prompt": False,
        "has_pointer": False,
        "has_prompt_passthrough": False,
    },
    "lingbot": {
        "guide_slug": "lingbot",
        "connection_name": "reactor/lingbot",
        "title": "LingBot",
        "max_prompt_characters": MAX_WORLD_PROMPT_CHARACTERS,
        "prompt_kind": "scene",
        "is_empty_prompt_allowed": False,
        "camera_axes": LINGBOT_CAMERA_AXES,
        "prompt_command": "set_prompt",
        "has_audio_prompt": False,
        "has_pointer": False,
        "has_prompt_passthrough": False,
    },
    "lingbot-world-2": {
        "guide_slug": "lingbot-world-2",
        "connection_name": "reactor/lingbot-world-2",
        "title": "LingBot World 2",
        "max_prompt_characters": MAX_WORLD_PROMPT_CHARACTERS,
        "prompt_kind": "scene",
        "is_empty_prompt_allowed": False,
        "camera_axes": LINGBOT_WORLD_CAMERA_AXES,
        "prompt_command": "set_prompt",
        "has_audio_prompt": False,
        "has_pointer": False,
        "has_prompt_passthrough": False,
    },
    "longlive-v2": {
        "guide_slug": "longlive-v2",
        "connection_name": "reactor/longlive-v2",
        "title": "LongLive",
        "max_prompt_characters": MAX_PROMPT_CHARACTERS,
        "prompt_kind": "scene",
        "is_empty_prompt_allowed": False,
        "camera_axes": (),
        "prompt_command": "set_shot",
        "has_audio_prompt": False,
        "has_pointer": False,
        "has_prompt_passthrough": False,
    },
    "sana-streaming": {
        "guide_slug": "sana-streaming",
        "connection_name": "reactor/sana-streaming",
        "title": "SANA",
        "max_prompt_characters": MAX_PROMPT_CHARACTERS,
        "prompt_kind": "edit",
        "is_empty_prompt_allowed": True,
        "camera_axes": (),
        "prompt_command": "set_prompt",
        "has_audio_prompt": False,
        "has_pointer": False,
        "has_prompt_passthrough": False,
    },
    "ltx2": {
        "guide_slug": "ltx",
        "connection_name": "reactor/ltx2",
        "title": "LTX",
        "max_prompt_characters": MAX_PROMPT_CHARACTERS,
        "prompt_kind": "scene",
        "is_empty_prompt_allowed": False,
        "camera_axes": (),
        "prompt_command": "set_prompt",
        "has_audio_prompt": False,
        "has_pointer": False,
        "has_prompt_passthrough": False,
    },
    "x2": {
        "guide_slug": "x2",
        "connection_name": "xmax/x2",
        "title": "X2",
        "max_prompt_characters": MAX_EDIT_PROMPT_CHARACTERS,
        "prompt_kind": "edit",
        "is_empty_prompt_allowed": False,
        "camera_axes": (),
        "prompt_command": "set_prompt",
        "has_audio_prompt": False,
        "has_pointer": True,
        "has_prompt_passthrough": False,
    },
}

__all__ = ["MODEL_IDENTITIES"]
